# Generated by Django 3.1.3 on 2021-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210217_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
    ]
