# Generated by Django 3.1.3 on 2021-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='importation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
    ]
