# Generated by Django 3.1.3 on 2021-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_20210217_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=2, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de Origen'),
        ),
    ]
